### PR TITLE
Fix whitespace issues

### LINKED ISSUE #11: Strip leading/trailing whitespace

### PR DESCRIPTION
**Pull request by MatthijsBurgh**
Problem occurs in yaml when tabs are followed by a comment.

The solution is generic and used by all loaders as I don't think whitespace is functional here.

Fixes #11

Merge after: tue-robotics/ed_navigation#15, tue-robotics/ed_gui_server#18 and tue-robotics/ed_localization#8

### CODE REVIEW

File: test/sdf_gtest.cpp [hunk 1]
```diff
@@ -6,7 +6,7 @@
 
 #include "tue/filesystem/path.h"
 
-tue::config::ReaderWriter config;
+static tue::config::ReaderWriter config;
```
Comment (alberth) [inline test/sdf_gtest.cpp]: I would expect the store to be setup as part of each test, instead of being shared, as now tests may influence each other leading to false test results.

**Comment by alberth** [comment]
Aside from the test thing, patch looks fine to me.

File: test/sdf_gtest.cpp (hunk 1 above)
Comment (MatthijsBurgh) [reply test/sdf_gtest.cpp]: I reverted the addition of the static. I don't know anymore why I did it.

The tests do 'depend' on the previous tests. At least on bringing the object to a correct state. It isn't the cleanest way. If this is really wrong, I will create an issue, so this can be fixed in an other PR. So let me know.

Comment (MatthijsBurgh) [reply test/sdf_gtest.cpp]: @alberth please see my previous comment.

**Comment by alberth** [comment]
Simplest way to fix is to create a clean new object for each test, and then get it in the proper state for each test by calling whatever previous tests you need to call first.

Obviously, a test that is also used in another test is useless as test by itself since its test is also performed by "another test". It's a "fake test", looks good in test count, but it is not testing anything that isn't covered by other tests already.
You can simply drop those fake tests as test (you still need the code for the "another test" that uses it though). That should also be a simple thing to change.

The complicated part comes in finding better tests, which do proper testing. Making a new issue for it is likely useless, as nobody is going to fix that I think.

**Comment by MatthijsBurgh** [comment]
@alberth No, I will fix that at a later point. Could please review the rest of this PR?
